import { User, Resource, Loan, Request } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Arjun Mehta",
    email: "arjun.mehta@university.edu",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    department: "Computer Science",
    year: "3rd Year",
    isVerified: true,
    trustScore: 94,
    rating: 4.8,
    successfulExchanges: 23,
    lateReturns: 1,
    disputes: 0,
    role: "student",
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya.sharma@university.edu",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    department: "Media Studies",
    year: "2nd Year",
    isVerified: true,
    trustScore: 88,
    rating: 4.6,
    successfulExchanges: 15,
    lateReturns: 2,
    disputes: 0,
    role: "student",
  },
  {
    id: "u3",
    name: "Rahul Nair",
    email: "rahul.nair@university.edu",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    department: "Electronics Engineering",
    year: "4th Year",
    isVerified: true,
    trustScore: 97,
    rating: 4.9,
    successfulExchanges: 41,
    lateReturns: 0,
    disputes: 0,
    role: "student",
  },
  {
    id: "admin1",
    name: "Dr. Kavita Reddy",
    email: "admin@university.edu",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
    department: "Administration",
    year: "Faculty",
    isVerified: true,
    trustScore: 100,
    rating: 5.0,
    successfulExchanges: 120,
    lateReturns: 0,
    disputes: 0,
    role: "admin",
  },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "r1",
    title: "Sony Alpha A7 III Mirrorless Camera",
    category: "Cameras",
    description:
      "Full-frame mirrorless camera with 24.2MP sensor. Perfect for photography projects, college events, and media assignments. Comes with 28-70mm kit lens.",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop",
    ],
    ownerId: "u2",
    ownerName: "Priya Sharma",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 88,
    ownerVerified: true,
    condition: "Excellent",
    isAvailable: true,
    distanceKm: 0.3,
    rating: 4.8,
    reviewCount: 12,
    hourlyRate: 50,
    dailyRate: 300,
    securityDeposit: 5000,
    accessories: ["28-70mm Kit Lens", "Camera Bag", "2x Batteries", "Charger", "64GB SD Card"],
    borrowingConditions: [
      "Must have completed camera handling orientation",
      "No outdoor shoots during rain",
      "Return with full charge",
      "Report any damage immediately",
    ],
    matchScore: 97,
    tags: ["photography", "video", "events", "mirrorless"],
    usageHistory: [
      { userId: "u1", userName: "Arjun Mehta", date: "2026-08-01", rating: 5, review: "Camera was in pristine condition. Priya was very helpful!" },
      { userId: "u3", userName: "Rahul Nair", date: "2026-07-15", rating: 5, review: "Perfect for our tech fest coverage." },
    ],
  },
  {
    id: "r2",
    title: "DJI Mavic Air 2 Drone",
    category: "Cameras",
    description:
      "4K drone with 3-axis stabilization. Ideal for aerial photography of campus events, fests, and architectural documentation projects.",
    images: [
      "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&h=600&fit=crop",
    ],
    ownerId: "u3",
    ownerName: "Rahul Nair",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 97,
    ownerVerified: true,
    condition: "Good",
    isAvailable: false,
    availableFrom: "2026-09-02",
    distanceKm: 0.8,
    rating: 4.7,
    reviewCount: 8,
    dailyRate: 600,
    securityDeposit: 8000,
    accessories: ["2x Batteries", "Remote Controller", "Carrying Case", "ND Filters"],
    borrowingConditions: [
      "Valid DGCA drone flying permit required",
      "No flying within 5km of airport",
      "Must purchase travel insurance",
    ],
    matchScore: 82,
    tags: ["drone", "aerial", "4k", "photography"],
    usageHistory: [
      { userId: "u1", userName: "Arjun Mehta", date: "2026-07-20", rating: 5, review: "Incredible shots for our annual day!" },
    ],
  },
  {
    id: "r3",
    title: "MacBook Pro 14-inch (M3 Pro)",
    category: "Electronics",
    description:
      "Apple MacBook Pro with M3 Pro chip, 18GB RAM, 512GB SSD. Ideal for coding marathons, video editing, and design sprints.",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=600&fit=crop",
    ],
    ownerId: "u1",
    ownerName: "Arjun Mehta",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 94,
    ownerVerified: true,
    condition: "Excellent",
    isAvailable: true,
    distanceKm: 0.1,
    rating: 4.9,
    reviewCount: 18,
    dailyRate: 400,
    securityDeposit: 15000,
    accessories: ["USB-C Charger", "MagSafe Cable", "Laptop Sleeve"],
    borrowingConditions: [
      "No software installations without permission",
      "Return with 50%+ battery",
      "Laptop must be cleaned before return",
    ],
    matchScore: 91,
    tags: ["laptop", "coding", "design", "video editing"],
    usageHistory: [
      { userId: "u2", userName: "Priya Sharma", date: "2026-08-10", rating: 5, review: "Blazing fast for video editing!" },
      { userId: "u3", userName: "Rahul Nair", date: "2026-07-28", rating: 5, review: "Perfect for our hackathon." },
    ],
  },
  {
    id: "r4",
    title: "Rode NT-USB Condenser Microphone",
    category: "Electronics",
    description:
      "Studio-quality USB condenser microphone for podcasting, voiceovers, music recording, and video productions.",
    images: [
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=600&fit=crop",
    ],
    ownerId: "u2",
    ownerName: "Priya Sharma",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 88,
    ownerVerified: true,
    condition: "Good",
    isAvailable: true,
    distanceKm: 0.3,
    rating: 4.6,
    reviewCount: 9,
    dailyRate: 150,
    securityDeposit: 2000,
    accessories: ["Pop Filter", "Mic Stand", "USB Cable", "Shock Mount"],
    borrowingConditions: ["Handle with care", "No outdoor use", "Return in original case"],
    matchScore: 95,
    tags: ["microphone", "podcast", "recording", "audio"],
    usageHistory: [],
  },
  {
    id: "r5",
    title: "Introduction to Algorithms — CLRS 4th Edition",
    category: "Books",
    description:
      "The classic algorithms textbook by Cormen, Leiserson, Rivest, and Stein. Essential for CS fundamentals, placements, and competitive programming.",
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=600&fit=crop",
    ],
    ownerId: "u3",
    ownerName: "Rahul Nair",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 97,
    ownerVerified: true,
    condition: "Good",
    isAvailable: true,
    distanceKm: 0.8,
    rating: 4.7,
    reviewCount: 22,
    dailyRate: 30,
    securityDeposit: 500,
    accessories: [],
    borrowingConditions: ["No marking or highlighting", "Return within 7 days max"],
    matchScore: 75,
    tags: ["algorithms", "textbook", "CS", "placement"],
    usageHistory: [],
  },
  {
    id: "r6",
    title: "Yamaha P-45 Digital Piano",
    category: "Music",
    description:
      "88-key weighted digital piano with realistic grand piano touch. Perfect for music practice, compositions, and college cultural events.",
    images: [
      "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&h=600&fit=crop",
    ],
    ownerId: "u1",
    ownerName: "Arjun Mehta",
    ownerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 94,
    ownerVerified: true,
    condition: "Excellent",
    isAvailable: true,
    distanceKm: 0.1,
    rating: 4.9,
    reviewCount: 6,
    dailyRate: 200,
    securityDeposit: 3000,
    accessories: ["Power Adapter", "Sustain Pedal", "Stand", "Bench"],
    borrowingConditions: ["Transport carefully with padding", "No liquids near keyboard"],
    matchScore: 68,
    tags: ["piano", "music", "cultural events", "keyboard"],
    usageHistory: [],
  },
  {
    id: "r7",
    title: "Projector + Screen Combo (Full HD)",
    category: "Event Equipment",
    description:
      "Epson 3500-lumen full HD projector with 100-inch motorized screen. Ideal for seminars, movie nights, club presentations, and workshops.",
    images: [
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&h=600&fit=crop",
    ],
    ownerId: "u3",
    ownerName: "Rahul Nair",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 97,
    ownerVerified: true,
    condition: "Excellent",
    isAvailable: true,
    distanceKm: 0.8,
    rating: 4.8,
    reviewCount: 14,
    hourlyRate: 100,
    dailyRate: 500,
    securityDeposit: 6000,
    accessories: ["HDMI Cable", "VGA Adapter", "Remote", "Extension Cord", "Carrying Case"],
    borrowingConditions: [
      "Setup assistance available on request",
      "Return projector lamp-hours logged",
      "No outdoor use without weatherproofing",
    ],
    matchScore: 88,
    tags: ["projector", "presentation", "events", "seminar"],
    usageHistory: [],
  },
  {
    id: "r8",
    title: "Cricket Kit (Full Set)",
    category: "Sports",
    description:
      "Complete cricket kit including bat, pads, helmet, gloves, and stumps. For inter-college matches and practice sessions.",
    images: [
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&h=600&fit=crop",
    ],
    ownerId: "u2",
    ownerName: "Priya Sharma",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    ownerTrustScore: 88,
    ownerVerified: true,
    condition: "Good",
    isAvailable: true,
    distanceKm: 0.5,
    rating: 4.4,
    reviewCount: 7,
    dailyRate: 200,
    securityDeposit: 2000,
    accessories: ["Bat", "2x Pads", "Helmet", "Gloves", "Stumps + Bails", "Dukes Ball x3"],
    borrowingConditions: ["Return all accessories", "Check inventory on pickup"],
    matchScore: 62,
    tags: ["cricket", "sports", "outdoor", "team"],
    usageHistory: [],
  },
];

export const MOCK_LOANS: Loan[] = [
  {
    id: "l1",
    resourceId: "r3",
    resourceTitle: "MacBook Pro 14-inch (M3 Pro)",
    resourceImage: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=300&fit=crop",
    borrowerId: "u1",
    lenderId: "u1",
    lenderName: "Arjun Mehta",
    startDate: "2026-08-25",
    endDate: "2026-08-29",
    status: "active",
    dailyRate: 400,
    deposit: 15000,
    totalCost: 1600,
  },
  {
    id: "l2",
    resourceId: "r7",
    resourceTitle: "Projector + Screen Combo (Full HD)",
    resourceImage: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400&h=300&fit=crop",
    borrowerId: "u1",
    lenderId: "u3",
    lenderName: "Rahul Nair",
    startDate: "2026-08-20",
    endDate: "2026-08-21",
    status: "returned",
    dailyRate: 500,
    deposit: 6000,
    totalCost: 500,
  },
];

export const MOCK_REQUESTS: Request[] = [
  {
    id: "req1",
    resourceId: "r1",
    resourceTitle: "Sony Alpha A7 III Mirrorless Camera",
    resourceImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=300&fit=crop",
    requesterId: "u1",
    ownerId: "u2",
    ownerName: "Priya Sharma",
    requestedFrom: "2026-08-28",
    requestedTo: "2026-08-30",
    message: "Need it for the annual day photography coverage for the CS department.",
    status: "pending",
    createdAt: "2026-08-27",
  },
  {
    id: "req2",
    resourceId: "r4",
    resourceTitle: "Rode NT-USB Condenser Microphone",
    resourceImage: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=300&fit=crop",
    requesterId: "u1",
    ownerId: "u2",
    ownerName: "Priya Sharma",
    requestedFrom: "2026-08-28",
    requestedTo: "2026-08-30",
    message: "For our podcast recording session for the college tech club.",
    status: "approved",
    createdAt: "2026-08-26",
  },
];

export const CURRENT_USER = MOCK_USERS[0];
export const ADMIN_USER = MOCK_USERS[3];

export const CATEGORY_CONFIG = {
  Cameras: { color: "bg-violet-100 text-violet-700", accent: "bg-violet-500", emoji: "📷" },
  Electronics: { color: "bg-blue-100 text-blue-700", accent: "bg-blue-500", emoji: "💻" },
  Books: { color: "bg-yellow-100 text-yellow-700", accent: "bg-yellow-500", emoji: "📚" },
  Sports: { color: "bg-lime-100 text-lime-700", accent: "bg-lime-500", emoji: "⚽" },
  Music: { color: "bg-coral-100 text-coral-700", accent: "bg-orange-500", emoji: "🎵" },
  "Event Equipment": { color: "bg-pink-100 text-pink-700", accent: "bg-pink-500", emoji: "🎤" },
};
